trailing_comma:
  mandatory_comma: true

disabled_rules:
  - block_based_kvo
  - line_length

opt_in_rules:
  - attributes
  - closure_spacing
  - empty_count
  - explicit_init
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
