included:
  - Stark

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Stark
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/  Copyright © \d{4} Rusty Robots\. All rights reserved\.
                    \/\/
identifier_name:
  excluded:
    - id
line_length: 120
number_separator:
  minimum_length: 5
